// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Registro_Con_Detalle.DAL;

namespace Registro_Con_Detalle.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("Registro_Con_Detalle.Entidades.Ordenes", b =>
                {
                    b.Property<int>("OrdenesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.HasKey("OrdenesId");

                    b.ToTable("Ordenes");
                });

            modelBuilder.Entity("Registro_Con_Detalle.Entidades.OrdenesDetalle", b =>
                {
                    b.Property<int>("OrdenesDetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrdenesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("precio")
                        .HasColumnType("REAL");

                    b.HasKey("OrdenesDetalleId");

                    b.HasIndex("OrdenesId");

                    b.ToTable("OrdenesDetalle");
                });

            modelBuilder.Entity("Registro_Con_Detalle.Entidades.Producto", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.HasKey("ProductoId");

                    b.ToTable("Producto");

                    b.HasData(
                        new
                        {
                            ProductoId = 1,
                            Nombre = "Coca-cola"
                        },
                        new
                        {
                            ProductoId = 2,
                            Nombre = "Oreo"
                        },
                        new
                        {
                            ProductoId = 3,
                            Nombre = "KitKat"
                        },
                        new
                        {
                            ProductoId = 4,
                            Nombre = "Pringles"
                        },
                        new
                        {
                            ProductoId = 5,
                            Nombre = "Snickers"
                        },
                        new
                        {
                            ProductoId = 6,
                            Nombre = "Pepsi"
                        });
                });

            modelBuilder.Entity("Registro_Con_Detalle.Entidades.OrdenesDetalle", b =>
                {
                    b.HasOne("Registro_Con_Detalle.Entidades.Ordenes", null)
                        .WithMany("OrdenesDetalles")
                        .HasForeignKey("OrdenesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Registro_Con_Detalle.Entidades.Ordenes", b =>
                {
                    b.Navigation("OrdenesDetalles");
                });
#pragma warning restore 612, 618
        }
    }
}
